- src/twig.functions.js
- test/test.functions.js
This pull request implements a ``random`` function that matches the behavior of the ``twig_random`` function that appears here:
https://github.com/fabpot/Twig/blob/7c63a7df8a9d38ff9eb9fb982ae8f6a70258c10c/lib/Twig/Extension/Core.php#L386
> Implement random function

- src/twig.functions.js
> Update random function to make it working more correctly

- src/twig.core.js
- src/twig.logic.js
- test/templates/use-override-block.twig
- test/templates/use.twig
- test/test.block.js
> Allow overriding of imported blocks

- src/twig.core.js
- src/twig.exports.js
- src/twig.filters.js
- src/twig.functions.js
- src/twig.logic.js
- test/test.core.js
- test/test.filters.js
- test/test.functions.js
> Autoescape feature (not enabled by default yet)

- src/twig.logic.js
- test/templates/blocks-nested-multiple.twig
- test/templates/use-override-nested-block.twig
- test/test.block.js
> Fix imported nested blocks overriding

- src/twig.tests.js
- test/test.tests.js
This implements the ``iterable`` test.
In addition, it checks for an ES6 iterable function on passed in values.
> Implement iterable test

- src/twig.logic.js
- test/test.controlStructures.js
> "For" tag optimization

- src/twig.logic.js
- test/test.core.js
> Return a Twig.Markup instance from parent()

- src/twig.lib.js
> Update the "strtotime" function

- src/twig.logic.js
- test/templates/macro.twig
> Macro supports whitespace characters around parentheses now

- src/twig.core.js
- src/twig.functions.js
- src/twig.logic.js
- test/test.block.js
> Fix the 'block' function to respect changes of the context

- src/twig.lib.js
I copy-pasted the source from https://github.com/alexei/sprintf.js/blob/master/src/sprintf.js
and changed https://github.com/alexei/sprintf.js/blob/master/src/sprintf.js#L188-L207 to just return the functions that we need
> Update sprintf to v1.0.3

- src/twig.core.js
- test/test.regression.js
> Ignore quotes between {% raw %} and {% endraw %}

- src/twig.core.js
in old version (for example 0.8.3) compilation is made in template context.
I add context binding
> fix compilation bug

- src/twig.core.js
See https://github.com/justjohn/twig.js/pull/252 for details.
> Normalize provided template path.

- src/twig.core.js
- src/twig.filters.js
- test/test.core.js
- test/test.filters.js
Support all available escape-strategies also for the autoescape option for compiling templates.
> Autoescape: support alternative strategies for autoescape option

- src/twig.exports.js
Defensive code and clean up in Twig.exports.renderFile in an attempt to fix issue #302
> Fix Twig.renderFile (issue #302)

- src/twig.expression.js
- test/test.tests.js
> Fix "is defined" test

- src/twig.path.js
- test/namespaces.twig
- test/templates/namespaces/namespaces.twig
- test/templates/namespaces_::.twig
- test/templates/namespaces_@.twig
- test/test.namespaces.js
Re-implements #320. Thanks to @gravypower.
> Allow namespaces to be defined with '@'

- Makefile
- src/twig.core.js
- src/twig.exports.js
- src/twig.functions.js
- src/twig.loader.ajax.js
- src/twig.loader.fs.js
- src/twig.parser.source.js
- src/twig.parser.twig.js
- test/index.html
- test/templates/source.twig
- test/test.functions.js
- test/test.parsers.js
Hello,
This pull request implements twig's [source](http://twig.sensiolabs.org/doc/functions/source.html) function, utilizing existing logic from ``` Twig.Templates.loadRemote ```.
> Source function implementation

- src/twig.logic.js
- test/test.logic.js
> Clone value of set when using context

- src/twig.exports.js
> Export Twig.js filters

- package.json
- src/twig.lib.js
This reduces our build size by about 400kb.
> Directly require phpjs functions

- src/twig.expression.js
- src/twig.expression.operator.js
- test/test.expressions.js
- test/test.expressions.operators.js
Turns out we completely fail to parse negative numbers!
> Fix negative number parsing and // flooring

- src/twig.expression.js
- src/twig.expression.operator.js
- test/test.expressions.js
- test/test.expressions.operators.js
> Support extended ternary operator (?:)

- src/twig.expression.js
- test/test.expressions.js
> Allow expressions after period accessor

- package.json
- webpack.config.js
> Add browser specific build to webpack

- src/twig.expression.js
- test/test.expressions.js
> Add support for slice shorthand

- src/twig.functions.js
- test/test.filters.js
Currently you get the fail case date.
> Allow empty strings to the date filter

- package.json
- src/twig.lib.js
> Update phpjs to locutus. Fixes #375

- test/browser/test.namespace.js
- test/templates/namespaces_::.twig
- test/templates/namespaces_coloncolon.twig
- test/test.namespaces.js
> Fix windows colon colon namespace

- src/twig.async.js
> Fix issues #461 #470 - Unexpected keyword 'const'

- src/twig.expression.operator.js
- test/test.expressions.js
> Fix incorrect "and" and "or" behaviour when simply comparing variables

- README.md
- package.json
For #490 - makes the package.json `engines` match what Travis tests.
> update `engines`' node version to match travis

- src/twig.logic.js
- test/test.tags.js
Currently this library does not support the `with` tag, this PR adds it.
https://twig.symfony.com/doc/2.x/tags/with.html
> Added support for with tag.

- demos/node_express/app.js
- src/twig.core.js
- src/twig.exports.js
- src/twig.loader.fs.js
- src/twig.path.js
- test/test.loaders.js
- test/test.path.js
- test/test.rethrow.js
> Revert "fixes #250 Node_express demo throwing errors"

- src/twig.async.js
- src/twig.core.js
- src/twig.exports.js
- src/twig.expression.js
- src/twig.logic.js
- src/twig.path.js
- test/test.async.js
Related to issues discussed in https://github.com/twigjs/twig.js/pull/486#issuecomment-311320349
> Performance improvements when including templates.

- src/twig.filters.js
- test/test.filters.js
This is a simple fix for issue #514 
I've added a test, which passes. However the tests as a whole fail due to another unrelated test case failing.
Let me know if you want anything changing!
> Added date support for json_encode filter

- test/templates/include/relative.twig
- test/test.fs.js
Being discussed, related to https://github.com/twigjs/twig.js/issues/545
> [include] add test case for relative paths

- README.md
- src/twig.exports.js
- test/templates/test-async.twig
- test/test.exports.js
Adds support for Express asynchronous Twig rendering (https://github.com/twigjs/twig.js/issues/553)
> [async][express] allow express to render async

- test/test.factory.js
- I left in an exclusive mocha test by accident
- for consistency, I removed my usage of `const`
> Fix issues introduced by tests in #561

- src/twig.path.js
- test/templates/namespaces/one/namespaces.twig
- test/templates/namespaces/two/namespaces.twig
- test/templates/namespaces_multiple.twig
- test/test.namespaces.js
Addresses #567 
Changes the namespace regex to take the namespace key into account, so that multiple namespaces can be resolved.
> Allow for multiple namespace resolutions

- src/twig.logic.js
> Fix bug in 'for' loop

- src/twig.expression.operator.js
Replace `.startsWith` and `.endsWith` to `.indexOf`
> Fix for IE

- package.json
Match what's tested:
https://github.com/twigjs/twig.js/blob/master/.travis.yml
> Update npm engine to >= 6

- src/twig.path.js
- test/browser/test.namespace.js
- test/test.namespaces.js
> Add possibility to define namespace without slash at the end of the path

- package-lock.json
- package.json
- test/test.rethrow.js
I could've updated Mocha as well but updating it to the latest stable version causes one of the tests to fail.
> Update development dependencies

- src/twig.async.js
- src/twig.core.js
- src/twig.expression.js
- src/twig.filters.js
- src/twig.functions.js
- src/twig.logic.js
- test/browser/test.block.js
- test/test.block.js
- test/test.extends.js
This brings the `develop` branch inline with the `master` branch and cleanly merges it into `master`.
This means that the block re-implementation is ready for release. This will require a v2.0.0 release because of the BC breaks.
@RobLoach you can do a pre-release version for v2.0.0 if you want to let people test before release, up to you. It might be nice though, I'd be glad to go through all the fixed issues and add a note about the pre-release version so those who submitted the specific issues can be test against their real-world usages.
> Merge block re-implementation for release

- lib/compile.js
- lib/paths.js
- package-lock.json
- package.json
- src/twig.async.js
- src/twig.compiler.js
- src/twig.core.js
- src/twig.exports.js
- src/twig.expression.js
- src/twig.expression.operator.js
- src/twig.filters.js
- src/twig.functions.js
- src/twig.lib.js
- src/twig.loader.ajax.js
- src/twig.loader.fs.js
- src/twig.logic.js
- src/twig.path.js
- src/twig.tests.js
Prior Travis builds were failing due to `package-lock.json` not including `xo`. I took this as an opportunity to not just include the dependency in `package-lock.json` but to also regenerate the lock file from scratch.
> XO Updates

- src/twig.logic.js
- test/test.tags.js
> Add support apply tag

- src/twig.filters.js
- test/test.filters.js
The spaceless filter was added in Twig 1.38
https://twig.symfony.com/doc/2.x/filters/spaceless.html
> Add filter spaceless

- src/twig.logic.js
- test/test.tags.js
This is a must to support existing templates.
> support for "do" tag

- webpack.config.js
> Provides sourcemaps

- src/twig.core.js
- test/test.inheritance.js
> search for block within all ascendants instead of parent only.

- package.json
Affects https://github.com/twigjs/twig.js/issues/684 .
> fix: Update engine in package.json to >= 8.16

- src/twig.exports.js
As @dave-irvine commented on #509
> Async renderFile error callback

- src/twig.logic.js
- test/templates/macro-self-twice.twig
- test/test.macro.js
> fix: fix lost context when calling a macro multiple times

- README.md
Fixed Twig official's URL on README.md
> Fixed Twig official's URL on README.md

- test/test.exports.js
Closes #509 since #748 actually fixed it, but did not include a test.
> Add test to confirm `renderFile` error handling

- ASYNC.md
- README.md
This resolves #706 by updating the docs.
> Fix casing of variables in docs

- src/twig.logic.js
- test/test.logic.js
> Allow multiple spaces after elseif statement.

- src/twig.expression.js
- src/twig.expression.operator.js
- test/test.expressions.js
> Add support for spaceship operator
