src/twig.core.js
IE 7 throw an exception because of it in some cases.
=> Fix for ie7

test/templates/macro.twig, twig.js
Adding white space around the parameters of a macro will cause the parser to throw an exception. I believe this is a bug because it seems counter intuitive (white space mattering) and I didn't see any mention of significant white space in the twig documentation.
A work around would be removing the white space.
I've added a test which fails, I'm very sorry but at the moment I don't have the time to look in it and create a patch.
=> Breaking test because of whitespace

src/twig.filters.js, test/test.filters.js
Makes `date` filter work correctly with an undefined value and an empty date format
Fixes #227
=> Fix `date` filter behavior

demos/node_express/public/vendor/twig.js, demos/twitter_backbone/vendor/twig.js, src/twig.functions.js, src/twig.lib.js, twig.js
**I'll preface this PR with this:**
The behavior of PHP's ``min`` and ``max`` functionals when passed associative arrays is ... *interesting*.
Regrettably, I've included the ``max`` and ``min`` functions from phpjs to ensure full compatibility. (The ``max`` and ``min`` functions are 90% similar and very long for what they do.)
There's much better ways to implement this using native ``Array.sort()`` and ``Math.max()`` and ``Math.min()``... however, the result doesn't behave as ``min`` and ``max``, so it won't pass the unit tests.
I didn't hack apart ``min`` and ``max`` to save a few bytes as gzip will take care of this. I would like to revisit any phpjs code we include to see if we can optimize some of the common code re-used between snippets.
=> Implement max and min functions

src/twig.expression.js, test/test.expressions.js
Adds an ability to use expressions as object keys:
```twig
{% set a = {foo: "bar"} %}
{% set b = {(a.foo): "value"} %}
{{ b.bar }}
```
will output `value`.
See http://twig.sensiolabs.org/doc/templates.html#literals:
> New in version 1.5: Support for hash keys as names and expressions was added in Twig 1.5.
=> Add support for expressions as object keys

src/twig.filters.js, test/test.filters.js
Implement the following strategies:
* html: (default, already implemented)
* js
* css
* url
* html_attr
The pull request also includes the commit of pull request #288 , as this filter is used for the strategy 'url'.
=> Filter 'escape': support strategy parameter

src/twig.filters.js, test/test.filters.js
In Twig.php the url_encode filter also encodes the apostrophe character. For this I added a test for url_encode, which tests encoding some special characters.
=> url_encode special characters (esp. the apostrophe)

src/twig.filters.js, test/test.filters.js
The PHP version of Twig allows default to be called without passing
any parameters, for example "{{ var|default|raw }}", with default
returning an empty string in this use case.
https://github.com/fabpot/Twig/blob/master/lib/Twig/Node/Expression/Filter/Default.php#L29
=>  Allow default filter to take 0 parameters

src/twig.functions.js, test/test.filters.js
=> Filter 'date': recognise unix timestamps, when passed as string

test/index.html
This PR fixes the browser tests for should.js (issue #281).
As per the README at https://github.com/shouldjs/should.js, you just need to include "should.js" in the browser to get it working.  That means the NPM module needs to be installed first, by running `npm i`
I don't think we need Chai anymore, but I did not want to remove the lib in test/lib/chai.js.  All tests are passing now without it.
=> issue #281 - fix should.js in browser

src/twig.logic.js, test/browser/test.block.js, test/test.block.js
Thought I would take a stab at this.  Let me know if there's a better way to do it.
This PR introduces block shortcuts (issue #293), as explained here: http://twig.sensiolabs.org/doc/tags/extends.html#block-shortcuts
Usage example:
```
{% block title page_title|title %}
```
Should be the same as:
```
{% block title %}
{{ page_title|title }}
{% endblock %}
```
=> issue #293 - support block shortcuts

Makefile, src/twig.core.js, src/twig.exports.js, src/twig.loader.ajax.js, src/twig.loader.fs.js, test/index.html, test/test.loaders.js
This is an attempt to fulfill Issue #294, [Request] override template loading mechanism(s).
This PR introduces a way for users to extend Twig and implement their own custom template loaders.  It also allows you to override previously defined loaders.
For example, load a template from redis:
```
var Twig = require('twig'),
redis = require('redis'),
client = redis.createClient();
Twig.extend(function(Twig) {
Twig.Templates.registerLoader('redis', function(location, params, callback, error_callback) {
var precompiled = params.precompiled;
if (typeof callback !== 'function') {
throw new Twig.Error('The params.load callback is required for the redis loader method');
}
if (!params.async) {
throw new Twig.Error('The "redis" loader method must be used asynchronously.');
}
client.get(location, …
```
=> Override template loading mechanism (Issue 294)

src/twig.expression.operator.js, test/test.expressions.js
replaces #270 
- support for `{{ ... in undefined }}` and `{{ ... in null }}`, as with #270 
- corrected return value (null instead of false)
- add tests
=> Support `undefined` and `null` values for the `in` operator

test/browser/test.namespace.js, test/index.html
#320 and #328 only includes tests for the filesystem loader; here are the tests for browsers.
=> Browser tests for #320 resp. #328: Namespaces with :: and @

src/twig.expression.js, test/test.expressions.js
This took a while to track down, but basically, doing the `return null;` as the original code does ends up in the object for which you are trying to get a property from being removed from the stack, and nothing going back on the stack to replace it. This is bad for chained expressions.
=> Undefined object keys corrupt stack

src/twig.expression.operator.js
We can remove duplication by popping the stack outside of the switch statement.
=> Simplify expression stack parsing

src/twig.exports.js, test/test.exports.js
Because https://github.com/expressjs/express/blob/b5a2801/lib/response.js#L136 does not work with `String`, which is created at https://github.com/twigjs/twig.js/blob/274a3ce830be07f10a9d1c09d7a2f671adceb649/src/twig.core.js#L1319
If this patch is not applied and you use twig.js with express like this:
``` js
app.set('twig options', {
autoescape: 'html'
});
```
then the returned value would be a "String" and not a "string". So express handles this by returning the value as `res.json()` :(.
So the html page looks like this:
``` json
"\n<!DOCTYPE HTML>\n<html la.."
``` 
Of course the HTML should not be delivered as JSON if the user wants the contents to be escaped ;).
PS: Workaround for others with the same issue:
``` js
app.engine('twig', function(path, options, fn) {
Twig.__express(path, …
```
=> Return rendered template as a string (for express)

src/twig.expression.operator.js, test/test.expressions.operators.js
I'd like some comments on this one before it gets merged from @plepe or @justjohn or @evgenius.
Our source states that we follow C operator precedence (https://en.wikipedia.org/wiki/Operators_in_C_and_C%2B%2B#Operator_precedence), but obviously there is no `in` statement in C.
The closest language I could find was JavaScript ;) https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Operator_Precedence and this puts `in` precedence at the same level as <,<=,>,>= so that is what I've done here.
All existing tests pass, my new test passes, but I've got a feeling this could really do with a larger suite considering the magnitude of the change.
Any thoughts appreciated!
=> Adjust in/not in operator precedence

src/twig.expression.js, test/test.expressions.js
I think this went in as part of Twig 1.5
```
{# keys as expressions (the expression must be enclosed into parentheses) -- as of Twig 1.5 #}
> { (1 + 1): 'foo', (a ~ 'b'): 'bar' }
```
=> Allow keys as expressions

src/twig.expression.js
Because `resolve()` can now call `parse()` we need to make sure to maintain the `this` context.
=> Call Twig.expression.resolve with the current 'this' context

src/twig.expression.js, test/test.expressions.js
This rabbit hole brought to you by:
```
{% if true is defined and (true) %}ok!{% endif %}
```
=> Add support for subexpressions

src/twig.lib.js, src/twig.logic.js, test/templates/extendee.twig, test/templates/extender.twig, test/test.extends.js
Previously, if your parent template `extends` another template, and in that "sub" template you do something with the context, like define a macro, these changes are not available in the parent template.
=> Update parent context when extending a template

src/twig.logic.js, test/test.controlStructures.js
This allows the `elseif` statement to accept the same values as the `if` statement by using loose comparison. A test is included.
=> Allow the `elseif` statement to accept truthy values

src/twig.expression.operator.js, src/twig.lib.js, src/twig.logic.js, test/test.controlStructures.js, test/test.expressions.js
This uses the `boolval` function from `locutus` in `if`, `elseif`, and ternary operations (`?`, `?:`) to determine what passes according to what PHP [considers falsy values](http://us2.php.net/manual/en/language.types.boolean.php#language.types.boolean.casting). Tests included.
=> Match what PHP considers falsy values

src/twig.expression.operator.js, test/test.expressions.js
Whenever `not` was in the second position of a binary operation like `and` or `or`, the entire operation would evaluate to `false` because the first expression would be popped off the stack even though the `not` operation would only apply to the second expression. When the `not` operation was found in the first position, the applicable expression was the only one in the stack, so popping the stack a second time had no effect and would appear to work correctly.
This PR only pops the stack once to get the applicable expression and then converts it to a boolean. Tests included.
=> Fix `not` operation occurring after binary operators

src/twig.logic.js, test/test.core.js
This fixes #394 and #231.
The context for the included file was being used to resolve the file name. When the `only` keyword was used, variables used in the filename could become undefined if they were not in a `with` statement. This changes it to always use the context of the `include` statement itself and not the included file.
Test included.
=> Use the current context when parsing include file name

src/twig.loader.fs.js, src/twig.logic.js, test/templates/embed-ignore-missing.twig, test/templates/include-ignore-missing-missing.twig, test/templates/include-ignore-missing.twig, test/test.embed.js, test/test.fs.js
This Pull Request adds correct handling of `ignore missing` for
[`include`](http://twig.sensiolabs.org/doc/tags/include.html) and [`embed`](http://twig.sensiolabs.org/doc/tags/embed.html)
=> Ignore missing

src/twig.core.js, test/test.rethrow.js
This PR ensure that when the rethrow option is set to true, any thrown exception is actually rethrown _and_ no logging is sent to the console.
=> Fix issue #335

src/twig.expression.js, src/twig.tests.js, test/test.tests.js
`sameas` is deprecated
Ref.: https://github.com/twigphp/Twig/blob/1.x/doc/deprecated.rst
=> Adding support of 'same as'

src/twig.loader.fs.js, test/test.fs.js
When using the fs loader, passing the async flag and an error callback function to `twig()` should ensure that if the loader encounters an error (such as "file not found", etc.) that it uses the given error callback.
Unfortunately, the fs loader currently throws an error and ignores the error callback when the file specified in `path` is not a file or does not exist.
Here's the fix. And I've added a test that fails if the fix is not implemented.
=> Ensure an error during async fs loading uses the error callback

src/twig.logic.js, test/test.tags.js
This fixes #372.
Previously this tag returned a pure string, but this means that when the output is later run through the output function, it will escape the output, which isn't what we want when Spaceless wraps static values.
=> Spaceless tag now re-wraps output as Twig.Markup

src/twig.logic.js, test/templates/from.twig
Aliases in `from` tag are ignored.
Test is passing, because it isn't actually testing for aliases.
This PR fixes:
- regular expressions for parsing aliases in `from` tag
- `from` tag test template to actually test for aliases
=> Fix 'from' tag logic and corresponding test

src/twig.expression.js, test/test.core.js, test/test.expressions.js
Before you could not use the `not` unary in the first position in an expression.
Tests included.
=> Allow the `not` unary to be used more widely in expressions

src/twig.core.js
- This was incorrectly implemented in #264.
- A later call to `Twig.path.parsePath` in the `render` function generates the correct file path after `importFile` failed to do so, but not before an error would be thrown.
If you look back over previous Travis CI logs you can see the test `Twig.js Blocks -> block shorthand -> should overload blocks from an extended template using shorthand syntax` in `test.block.js` would pass, [but a couple errors would still be emitted](https://travis-ci.org/twigjs/twig.js/jobs/134087980#L1373-L1429).
=> Fix handling of relative paths in the `importFile` function

src/twig.expression.js, test/test.functions.js
This PR fix the issue #440 by scoping functions call to the belonging object (if any) or to the context. Functions tests suite has also been improved to include object context test case.
=> Fix issue #440 - Object methods lose context when called

ASYNC.md, src/twig.async.js, src/twig.core.js, src/twig.expression.js, src/twig.js, src/twig.logic.js, test/test.async.js, test/test.filters.js, test/test.functions.js
Allows for functions and filters to return promises and render asynchronously (https://github.com/twigjs/twig.js/issues/61).
I've tried to build this PR based on the discussions in the original issue and some offline discussions with @Gertt. The currently implementation tries to change as little of the existing code as possible, but I had to restructure the implementation of some `logic`/`expression` code such that it would behave correctly when used with promises.
Only the `Twig.expression.parse`, `Twig.expression.resolve`, `Twig.parse` and `Twig.Template.render` methods are truly aware of the fact that promises are used internally. If the flag `allow_async` is set these methods will allow functions and filters to behave asynchronously, otherwise it will throw as soon as the asynchronous …
=> Asynchronous rendering and function/filter promises

package.json, test/hooks.js, test/test.async.js, test/test.block.js, test/test.controlStructures.js, test/test.core.js, test/test.embed.js, test/test.exports.js, test/test.expressions.js, test/test.expressions.operators.js, test/test.extends.js, test/test.filters.js, test/test.fs.js, test/test.functions.js, test/test.loaders.js, test/test.logic.js, test/test.macro.js, test/test.namespaces.js, test/test.options.js, test/test.parsers.js, test/test.path.js, test/test.regression.js, test/test.rethrow.js, test/test.tags.js, test/test.tests.js
This commit fix the issue by using [require-uncached](https://www.npmjs.com/package/require-uncached) to require twig in the tests suite.
Two macro tests have also been fixed since they were returning false positive due to the twig instance being polluted by previous tests.
=> Fix issue #463 - Test result is dependent on the name of the test file

demos/node_express/public/vendor/twig.js, demos/twitter_backbone/vendor/twig.js, docs/twig.html
Updates the embed regex in the docs and demo to match [twig.logic.js:1032](https://github.com/twigjs/twig.js/blob/master/src/twig.logic.js#L1032) (change introduced in dbf1fc7, which I think obviates #390)
=> update embed regex in demos and docs

src/twig.filters.js, test/test.filters.js
**Actual Behaviour:**
If autoescape = 'html' the following code:
```
{{ text | trim }}
```
with
```
test = '\r\n <a href="">Test</a>\n  '
```
will auto escape internally to:
```
&lt;a href=&quot;&quot;&gt;Test&lt;/a&gt;
```
so, it will escape just again afterwards to:
```
&amp;lt;a href=&amp;quot;&amp;quot;&amp;gt;Test&amp;lt;/a&amp;gt;
```
when it's printed.
A workaround is:
```
{{ text | trim | raw }}
```
**Expected behaviour:**
Escape only once.
**Steps taken**
0. Checked if twig php does the same thing https://github.com/twigphp/Twig/blob/fd98722d15996561f598f9181dbcef8432e9ff85/lib/Twig/Extension/Core.php#L158 ✅ 
1. Added failing test at https://travis-ci.org/twigjs/twig.js/builds/245690804 ✅ 
2. Fixed the test at https://travis-ci.org/twigjs/twig.js/builds/245691692 ✅ 
3. Created …
=> Bug: trim filter autoescapes

src/twig.async.js, src/twig.core.js, src/twig.expression.js, src/twig.filters.js, src/twig.functions.js, src/twig.lib.js, src/twig.logic.js, test/test.performance.js
As a result of https://github.com/twigjs/twig.js/issues/472 I've been looking into improving rendering performance. These changes reduce rendering times back to pre-async performance numbers.
**Updates**
- [Promise] Reduced the amount of closures used by a promise.
- [Promise] Reduced branching by replacing functions based on promise state.
- [Promise] Use numeric constants to check promise state.
- [Promise] Lazily convert `handlers` to an array.
- [Promise] Use `Twig.attempt` instead of `try/catch` ([optimization-killer](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#2-unsupported-syntax))
- [Promise] Move `append` out of constructor, js engine only has to optimize it once.
- [async/forEach] Reduce amount of closures.
- [async/forEach] Create less objects in memory. …
=> Rendering performance improvements

demos/node_express/app.js, src/twig.core.js, src/twig.exports.js, src/twig.loader.fs.js, src/twig.path.js, test/test.loaders.js, test/test.path.js, test/test.rethrow.js
A tiny fix that allows the node_express demo to work again. Without the 'twig options' defined twig would throw an exception.
I couldn't find any tests for the demo so I've not included any.
=> fixes #250 Node_express demo throwing errors

src/twig.logic.js
Looks like there is a missing "that" variable inside a "filter" token processing function that is causing a render exception.
=> Fixed an exception caused by a missing "that" reference

src/twig.core.js
Resolves https://github.com/twigjs/twig.js/issues/517
There are some intricacies involved in performing an `array.join`, so switched this back to the original (before #492).
```
[undefined,"",null,false].join('') // => "false"
undefined + "" + null + false // => undefinednullfalse
```
I could have changed [it](https://github.com/twigjs/twig.js/pull/518/files#diff-22566ec93dc04f3aa4f038de2fd55f29L921) to `escaped_output += str || ''` but behaviour would have been slightly different, specifically the `false`.
=> Fixes failing with only test

src/twig.logic.js, test/test.embed.js
There were some issues with using the `ignore missing` option in conjunction with the `only` option.
It turned out to be due to the regex not matching the options correctly and leaving the token with some missing variables. The regex was a little greedy trying to match after each option against the end of the string, which is not necessary.
- This also adds a set of more robust tests for all the available options.
=> Fix bugs in the `embed` tag options

src/twig.logic.js, test/test.async.js
For loops returned empty strings when using async rendering and async calls inside of the `for`-loop body.
=> [for] fixes empty loop output when containing async call

src/twig.core.js, src/twig.logic.js, test/test.embed.js
- This fixes #519.
- This is a stop-gap fix until I have completed re-implementing how blocks are parsed and handled, which will happen over a couple of PRs to keep things as simple as possible.
- This is a more robust way of checking if a block is being rendered inside of a for loop, working around issues with checking for the `loop` variable on the context since it is not present when excluded using `with` and `only`.
- A test that covers the bug reported in #519 is included.
=> Improve detection of when a block is in a loop

src/twig.logic.js, test/templates/macro-defaults.twig, test/test.macro.js
For Issue #531
Ability to defined default values for macro arguments:
```twig
{% macro input(name, value = "", type = "text", size = 20) %}
<input type="{{ type }}" name="{{ name }}" value="{{ value|e }}" size="{{ size }}" />
{% endmacro %}
```
=> Added the ability to set default values for macro arguments

.travis.yml, README.md, package.json, webpack.config.js
I just started using Twig.js and wanted to make some updates to `webpack.config.js` when I realized that we're still on Webpack 1! We should upgrade to the latest version, 4, to open us up to new plugins and performance enhancements.
This doesn't improve anything about the build size right now, but the build time has been reduced about a second.
=> Upgrade to Webpack 4

src/twig.lib.js, test/test.lib.js
When `add` is null, there would be an exception thrown. Having it force an empty object when add isn't there fixes the issue.
=> Fix extend when add is null

src/twig.logic.js, test/test.controlStructures.js
For issue #539
Now this:
```twig
{% for foo in [
'foo',
'bar
',  'baz'] %}
{{ foo }}
{% endfor %}
```
renders to this:
```
foo
bar
baz
```
=> Fix array declaration on multiple lines for `{% for ... in ... %}` tag

src/twig.logic.js, test/test.logic.js
Addresses #437 
Also fix test case for {% set %} and some misprints in comments
=> Fix twig `{% if(x) %}` and `{% elseif(x) %}` blocks parsing error

src/twig.logic.js, test/test.verbatim.js
Address issue #571
The `verbatim` tag marks sections as being raw text that should not be parsed. For example to put Twig syntax as example into a template you can use this snippet:
```
{% verbatim %}
<ul>
{% for item in seq %}
<li>{{ item }}</li>
{% endfor %}
</ul>
{% endverbatim %}
```
=> Add `verbatim` tag

src/twig.async.js, src/twig.core.js, src/twig.expression.js, src/twig.filters.js, src/twig.functions.js, src/twig.logic.js, test/test.extends.js
- This is a fairly large PR since the state while parsing a template touches a lot of the code. I have broken it down into smaller commits to hopefully make it easier to follow.
- The reason for this change was discovered while re-implementing how blocks are rendered. I realized that a lot of the issues were due to the fact that the parse "state" was being stored on the template itself. This makes it harder to manage that state and was leading to it being mishandled in multiple places. Especially when the same template was being rendered more than once by being embedded, and even more so when a template was rendering itself, within itself.
- By extracting all the code that pertains specifically to generic parsing of tokens, the state can be nested, initialized, and stored depending on the …
=> Extract parse state

src/twig.expression.js, src/twig.expression.operator.js, test/test.expressions.operators.js
=> Add support null-coalescing operator `??`

src/twig.core.js, test/test.core.js
Twig.js's autoescaping currently has some potentially unexpected behavior.
When autoescaping, the returned string object has a `twig_markup` value of true, which is unexpected and currently breaks certain usages of the twig module. For instance, you cannot insert this `String` as-is to your DOM, and must first call `.valueOf()`. I've changed the output to always return a properly formatted string, rather than this `String` object. This should not break any existing code, as you can still call `.valueOf()` on this newly returned string.
The more glaring problem however, is that the current version of twig.js doubly-escapes strings marked as `html_attr` with the `html` strategy. PHP Twig does not do this. I've added a fix for this.
Here's a quick demo of the problem. Given this template …
=> Autoescaping improvements

src/twig.filters.js, test/test.filters.js
The ability to encode an object to URL by the filter `url_encode` was added according to [the Twig PHP](https://twig.symfony.com/doc/2.x/filters/url_encode.html#url-encode).
```javascript
const data = {
foo: {
baz: 'bar',
},
};
const template = twig({ data: '{{ foo|url_encode }}' });
console.log(template.render(data)); // => "foo%5Bbaz%5D=bar"
```
=> Filter url_encode was extended for objects

src/twig.path.js
Fix to allow multiple namespaces
=> multiple namespaces fix

src/twig.core.js, src/twig.logic.js, test/test.core.js
The previous autoescaping improvement (https://github.com/twigjs/twig.js/pull/577) broke includes.
=> fix for not autoescaping includes

src/twig.async.js, src/twig.core.js, src/twig.functions.js, src/twig.logic.js, test/browser/test.block.js, test/test.block.js
As mentioned in #550, this is the final PR needed for fixing the biggest issues with blocks.
- This simplifies handling of blocks by more explicitly storing them, depending on how they are encountered while parsing. There are three "types" of blocks when it comes to parsing:
- `Defined Blocks` - These are blocks which are defined using the `{% block... %}` tag. They are stored on the `Twig.Template` instance where the `block` tag was parsed. They are stored with a reference to this template.
- `Imported Blocks` - These are blocks which are imported using the `{% use... %}` tag. This includes all the blocks resolved from the template referenced by the `use` tag. They are stored on the `Twig.Template` instance where the `use` tag was parsed.
- `Override Blocks` - These are blocks which are …
=> Reimplementation of  Blocks

package-lock.json, package.json, webpack.config.js
Terser can handle ES6 syntax unlike UglifyJS.
=> Replace UglifyJs with Terser as the webpack minimizer

src/twig.expression.js, test/test.functions.js
In some situations a function would be called on the `global` rather
than on the template instance.
=> [functions] fix function call on global object

src/twig.async.js, src/twig.core.js
The `Twig.attempt` function was used to work around the performance
issues of old versions of the V8 engine in regards to try-catch blocks.
Improvements in recent versions of the V8 engine allow for the
optimization of try-catch blocks.
Therefore, the `Twig.attempt` function is no longer needed.
=> Remove Twig.attempt function

src/twig.async.js, src/twig.core.js, src/twig.expression.js, src/twig.filters.js, src/twig.functions.js
The functions `Twig.indexOf` and `Twig.forEach` serve as polyfills for
`Array.prototype.indexOf` and `Array.prototype.forEach` respectively in
very old browsers such as IE8.
Modern browsers do not require these polyfills and neither does
Internet Explorer, because Internet Explorer has support for all Array
methods since IE9.
=> Remove polyfills for Array methods

package.json, webpack.config.js
`@babel/plugin-transform-modules-commonjs` is already included in
`@babel/preset-env`.
=> Remove redundant Babel plugin from package.json

package-lock.json, package.json, webpack.config.js
Instead of creating the server bundle and the browser bundle in two
separate Webpack builds, both bundles will be created in a single
Webpack build by having `webpack.config.js` export an array of
configuration objects.
In addition, the server build will not require transpilation as the
minimum supported NodeJS version (i.e. NodeJS 8) supports the use of
ES6 language features as is.
=> Streamline Webpack builds

src/twig.expression.operator.js, test/test.expressions.js
Fixes #660
Makes `starts with` and `ends with` expressions to not throw an error with non-string values.
Changes proposed in this pull request:
- Add a check for `starts with` and `ends with` expressions to check if it’s tested against a string.
- Add a test case where using `starts with` and `ends with` with an undefined variable.
=> Fix 'starts with' and 'ends with' expressions

src/twig.exports.js
Similar to #307
Use-case:
- I've found a bug in production e.g: #668
- I need to apply hotfix without forking.
I simply cannot do
```
// @see https://github.com/twigjs/twig.js/pull/668
window.Twig.filters.default = (value, _default = '') => {
if (window.Twig.tests.empty(value)) {
return _default;
}
return value;
};
```
=> Export tests

package.json
Add `license` key to /package.json (fixes npm complaining about missing license field)
=> Add npm license field

demos/node_express/public/vendor/twig.js, demos/twitter_backbone/vendor/twig.js, docs/twig.html, src/twig.core.js
That was broken after some past changes
Somehow related to #629
In `twig.exports.js` option param `strict_variables` was renamed to `strictVariables`.
This PR renames variable in other places
=> renames `strict_variables` option to `strictVariables`

src/twig.logic.js, test/test.tags.js
Compiling the 'deprecated' tag will result in a warning message in the console.
Note: The 'deprecated' tag was added PHP Twig 2.6, see: https://twig.symfony.com/doc/2.x/tags/deprecated.html.
=> Add support for 'deprecated' tag

README.md, src/twig.core.js, src/twig.exports.js, src/twig.expression.js, test/test.options.js
Makes it to match twigfeddle errors output
Example of new errors:
- `Variable "foo" does not exist.`
- `Key "key" for object with keys "a, b, c" does not exist.`
- `Key "key" does not exist as the object is empty.`
- `Key "10" for array with keys "0, 1, 2" does not exist.`
- `Key "10" does not exist as the array is empty.`
Live example: https://twigfiddle.com/yfnyxt
*Tip: you need to switch main template to see different output*
Closes #629
=> Fix strict_variables issues

src/twig.expression.operator.js, test/test.expressions.operators.js
The '??'-operator is very handy for setting default values. Like for example:
`{% set list = list ?? [] %}`
This works in PHP Twig. And it should of course work in twig.js too :)
=> Make '??'-operator return the actual array instead of array length

src/twig.logic.js, test/templates/include-array-second-exists.twig, test/templates/include-array.twig, test/test.fs.js
Adds support for the array syntax used with include. See https://twig.symfony.com/doc/3.x/tags/include.html
Fixes #468
=> #468 Support for including arrays of templates

src/twig.core.js, test/test.core.js
See test case, in the current release, it renders `[object Object]`
=> fix autoescape for empty includes

src/twig.filters.js, test/test.filters.js
See the new tests. Filters should handle empty string inputs.
The `escape` and `nl2br` filters failed to do that. Current behavior:
```twig
""|escape   --> [object Object]
""|nl2br    --> throws error
```
I also added some tests for other filters, based on this commit:
https://github.com/twigjs/twig.js/commit/2021d34caea0fcb721674a2cf0e742d5b945fe5f
=> Fix filters with empty string input

src/twig.core.js, src/twig.filters.js, test/test.filters.js
The raw filter return a new Markup(content) which may itself return content
if content is the empty string. The resulting output was `[Object]` instead of the expected empty string.
=> raw filter on the empty string

webpack.config.js
Hello community :)
Adding Babel transpilation on `serverBuild` for remove fat arrow `=>` and work on IE11.
In my case, i use Twig on client side only with `twigjs-loader`. This module load by default `twig.js` file, not working on IE11.
=> Add babel preset on serverBuild

src/twig.core.js, test/test.core.js
WhitespacePost/WhitespacePre trimmed the whole token, not only the
right/left part.
=> test + bugfix for whitespace trimming

src/twig.core.js
Checking for a line composed only by whitespaces is redundant, the
trimmig would take care of it anyway.
It also makes the code harder to read and is probably slower in most
cases (http://jsben.ch/wT1mz).
=> Simpler trimming logic

src/twig.filters.js, test/test.filters.js
While not unit tested, TwigPHP's `last` filter returns the last digit of
a number, not `""`.
With TwigPHP:
```twig
{{ 14|last }} # returns '4'
```
Currently, with twig.js
```twig
{{ 14|last }} # returns ''
```
See: https://twigfiddle.com/e28i2l
=> Fix `last` filter for numbers

src/twig.filters.js, test/test.core.js, test/test.filters.js
The ["js" escape strategy of Twig PHP](https://github.com/twigphp/Twig/blob/6384ba6c3ca7695ef0aec93bdf3b55c9bb18b5de/src/Extension/EscaperExtension.php#L247-L295) produces a JSON compatible escaping.
This is useful as it allows embedding JS escaped strings in JSON script.
For example, this can be used to templates JSON-LD scripts:
```html
<script type="application/ld+json">
{
"@context": "http://schema.org/",
"@type": "Person",
"name": "{{ name }}",
}
</script>
```
Unfortunately, the twig.js implementation doesn't produce JSON compatible escaping.
For example:
```js
const { twig } = require('twig');
const compiledTemplate = twig({ autoescape: 'js', data: '{{ foo }}' });
compiledTemplate.render({ foo: '<foo>' });
// > \x3Cfoo\x3E
```
`\x3Cfoo\x3E` is not [valid …
=> Make "js" escaped strings embeddable in JSON

src/twig.exports.js, src/twig.expression.operator.js, test/test.regression.js
fixing #737 making sure that ternary expression does not change context + exporting functions for test purposes
=> making sure that ternary expression does not change context

.npmignore, src/twig.async.js
Sometimes when a Twig file has a syntax error, for some reason the template object has no tokens to render, but it's sent to render anyway, causing an error. This should fix this error
=> Added token count validation

src/twig.loader.ajax.js
For twig.js to be used in the browser, it requires the user to know that they either must name their templates as an ending that browsers recognized (e.g. `txt` or `html`) or to manually register a mime-type to the `.twig` extension. Otherwise, when fetching a template, a browser will attempt to parse it using `text/xml` which can cause issues depending on strictness (e.g. #741).
This PR changes it so that twig.js always specifies that templates received via XMLHttpRequest are `text/plain` and to be treated as such.
=> Specify MimeType to always use for ajax templates

README.md
After trying to use Twig on the browser with `twig({...})` and getting ` ReferenceError: twig is not defined` I realized I needed to do `Twig.twig({...})` instead. 
If this not always the case let me know so I can improve the documentation in this regard. 
It can be seen happening here: https://jsbench.me/6gkgwawsrs/1. Notice the import from unpkg.
=> Update browser usage

src/twig.logic.js, test/templates/extendee-array.twig, test/templates/extender-array-none-exist.twig, test/templates/extender-array-second-exists.twig, test/templates/extender-array.twig, test/test.fs.js
This currently doesn't work:
```
{% extends ['one.twig', 'two.twig'] %}
```
See https://twig.symfony.com/doc/2.x/tags/extends.html#dynamic-inheritance under "You can also provide a list of templates that are checked for existence"
=> Add support for template arrays when using extends

src/twig.logic.js, test/templates/macro-context-loop.twig, test/test.macro.js
=> fix macro changing context in loop

bin/twigjs
Exported function `strip_slash()` renamed to `stripSlash()` causing twigjs compilation command fail.
=> Imported function PATHS.strip_slash() missing

.github/workflows/tests.yml, src/twig.lib.js
This adds a workflow to run the test suite. It currently only runs on pull requests, but could be expanded if needed.
This resolves #815.
=> Add GitHub actions test workflow

test/test.filters.js
This pull request adds tests for dates with timezone information, e.g.: `1995-12-17T08:24:00Z`, `1995-12-17T08:24:00+02:00`. The version with `Z` currently does not work. The problem is the strtodate function of locutus, which currently can't handle these strings (it has been fixed though, but not released yet).
Pull request which should eventually solve #726. Waiting for locutus release which incorporates locutusjs/locutus#432. I will update the pull request as soon as this release is available.
=> Fix date parsing with timezones

.gitmodules, test/test.fs.js
This expands the test suite to ensure that paths with leading or trailing whitespace are loaded correctly. This resolves #355.
=> Add tests for whitespace in paths

src/twig.logic.js, test/test.embed.js
This PR supersedes #784. After creating a failing test and debugging the issue, it turns out that the `id` should have never been set on the temporary template instance, since that stored it in the registry and allowed subsequent calls to the loader to return the temporary instance instead of the correct instance set before the embed.
Fixes #708
=> Fix multiple includes with embeds

test/test.embed.js
This resolves #767. The bug was actually fixed in #828, this PR just adds a test based specifically on the issue.
=> Add test for issue #767

docs/tests.md, src/twig.expression.js, src/twig.tests.js, test/test.tests.js
This deprecates `divisibleby` and updates references in the docs.
This resolves #804.
=> Add support for `divisible by` test

src/twig.logic.js, test/test.tags.js
=> Add support for `with` tag without context or `only` keyword

.github/workflows/tests.yml
This fixes the deprecation notice in the actions by using NodeJS v16 instead of v12.
@RobLoach I'm going ahead and merging this since it's so minor.
=> Use v3 of `actions/checkout`

.github/workflows/tests.yml, node/build.js, package.json
This supersedes #835 and tests up to Node v18.
I ended up creating a proxy script to run webpack and detect when Node v17+ is being used and add the Node flag accordingly.
=> Test on more node versions

src/twig.core.js, src/twig.logic.js, test/test.tags.js
This fixes #840 by allowing the context to be passed when initially creating an instance of `ParseState`. The old way of passing the context when calling `parse` is still supported to prevent BC breaks, but it no longer used internally.
=> Fix passing context around

src/twig.core.js, src/twig.expression.js, test/test.core.js
This PR adds the position to the tokens in the token tree. 
Example found in the following string:
`I want to {{ try }} a more {% if advanced | length > 3 %}{{ variable }}{% endif %} template {% set unit = 2 %}{# This is a comment #}{{ variable_after_comment }}`
```
{
type: 'raw',
value: ' template ',
position: { start: 82, end: 92 }
},
```
This means the raw text ` template ` can be found between position 82 and 92 in the given template.
This is one of a series of PRs I want to make to parse through tokens and to act on these tokens. Like the NodeTraverser of Twig in PHP.
=> Adds the (string) position of tokens to the token tree.

src/twig.expression.js, test/test.expressions.js
Fixes #854
Not sure why the colon is needed in de regexp for Twig.expression.type.key.brackets, @willrowe can you elaborate?
If it is not needed, removing the colon in the regexp will fix this issue.
=> Allow colon inside Twig.expression.type.key.brackets.

src/twig.expression.js, src/twig.filters.js, test/test.expressions.js, test/test.filters.js
=> Support variables in slice filter shorthand

src/twig.expression.js, test/test.expressions.operators.js
=> Allow whitespace in extended ternary operator for false conditions.
